### ISSUE TITLE
How to use MTP data to decrypt user_data

### ISSUE THREAD

**Issue by bvid34tgd** [ntqbit/tdesktop-decrypter#1]
Thanks for your tool. I got the output like this
```
Account 0:
MTP data:
User ID:
Main DC ID:
Key DC
```
What's the next step to decrypt data?

**Comment by baptx** [comment]
I got the same issue, it looks like it is not implemented:
https://github.com/ntqbit/tdesktop-decrypter/issues/2
Another solution is to use the "Export Telegram data" feature of Telegram Desktop  (in "Settings" -> "Advanced").

**Comment by klango** [comment]
> I got the same issue, it looks like it is not implemented: #2 Another solution is to use the "Export Telegram data" feature of Telegram Desktop (in "Settings" -> "Advanced").

Do you mean importing the tdata to a new installed Telegram Desktop?
Is it possible to do that knowing the passcode for decryption?

**Comment by ntqbit** [comment]
Media decryption is not implemented, only settings and MTP keys decryption are (although decrypted settings are not displayed).
