### ISSUE TITLE
Key DC 

### ISSUE THREAD

**Issue by klango** [ntqbit/tdesktop-decrypter#3]
What can one do with the Key DCs ?
Is it possible to decrypt the caches with them?

**Comment by ntqbit** [comment]
The DC key primarily serves for authentication in a specific data center, providing you access to the account for which this key was created. Even if the DC key was somehow involved in the encryption scheme, decryption wouldn't be straightforward. Having said that, the encryption scheme is open source, so you can write the decryptor yourself, perhaps even without using a DC key. Good luck!
